### ISSUE TITLE
Silent failure on duplicate clausedefs

### ISSUE THREAD

**Issue by maemre** [kyledewey/typed-prolog#13]
If there are duplicate `clausedef`s in a module for same clause, typed prolog fails silently instead of giving an error.

Both of the two examples fail silently (they don't get compiled but no error is printed, the compilation predicate in compiler fails silently), so the error happens both when `clausedef`s are completely identical and when only the predicate names are same:

``` prolog
module(test, [], []).

clausedef(test1, [], [int, int, int]).
clausedef(test1, [], [int, int, int]).
test1(X, Y, Z) :-
    X is Y.
```

``` prolog
module(test, [], []).

clausedef(test1, [], [int, int, int]).
clausedef(test1, [], [int, int, atom]).
test1(X, Y, Z) :-
    X is Y.
```

**Comment by kyledewey** [comment]
Out of curiosity, I tried the same thing for types, which revealed another problem, reported in issue #15.

**Comment by kyledewey** [comment]
Fixed with a series of commits, the last of which was 236260b0f997a0f9341c6a2b6f2db646900f629c.
