### ISSUE TITLE
Specific Atom is Broken

### ISSUE THREAD

**Issue by kyledewey** [kyledewey/typed-prolog#18]
The atom `<=` needs to be quoted in the context of a body.  That is, while this is valid:

``` prolog
foo(<=).
```

...this is not:

``` prolog
foo(Atom) :- Atom = <=.
```

In the later case, the addition of quotes is easy enough to fix things, like so:

``` prolog
foo(Atom) :- Atom = '<='.
```

This latter case is currently broken so that the quotes aren't emitted, so the compiled code cannot be parsed downstream.  This appears to be a bug in SWI-PL's [write_term/2](http://www.swi-prolog.org/pldoc/man?predicate=write_term/2) predicate.  Quotes aren't used even if `quoted(true)` is set, and looking at the code, it looks like this option only controls whether backslashes are used for special characters, not actual quotes.

Fixing this will require writing our own `write_term/2` predicate.

**Comment by maemre** [comment]
I played around with using `<=` without quotes under SWI-Prolog 7.2.3. Following doesn't get parsed:

``` prolog
foo(Atom) :- Atom = <=.
```

but this gets parsed correctly:

```prolog
foo(Atom) :- Atom = <= .
```

Changing [the line here](https://github.com/kyledewey/typed-prolog/blob/62dd4447d2d994d30ac97ea924e47442f8ecbe0a/src/io.pl#L56) with

```prolog
format(Stream, ' .~n', []).
```

to add a space before `.` should solve the issue.

**Comment by maemre** [comment]
@kyledewey I can write a patch and test it if you like the solution.

**Comment by kyledewey** [comment]
Initially I thought this would only fix things if the offending clause was last, so I tried:

```prolog
?- Atom = <=, Foo = bar.
```

The above code, however, works just fine.  As such, it _looks_ like this problem only affects unifications at the end of a clause body.  Moreover, I was also able to show that this works on SWI-PL 6.X, so I think this will work.

@maemre could you submit a pull request with the patch?
